version: "2"
networks:
  proxy:
    driver: bridge
services:
  backend-b2b:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./back-end
      dockerfile: Dockerfile
    image: laravel-b2b
    container_name: laravel-b2b
    environment:
      DEBUG: 'true'
    working_dir: /var/www
    depends_on: 
      - db-b2b
    networks:
        - proxy
    volumes:
      - ./back-end:/var/www
  front:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./front-end
      dockerfile: Dockerfile
    image: node:angular
    container_name: angular-b2b
    environment:
      DEBUG: 'true'
    working_dir: /var/www
    volumes:
      - ./front-end:/var/www
    networks:
      - proxy
  web:
    image: nginx:alpine
    container_name: nginx-b2b
    depends_on:
      - backend-b2b
      - front
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - backend-b2b
    ports:
      - 80:80
    networks:
      - proxy
  db-b2b:
    image: mysql
    container_name: db-b2b
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sort_buffer_size=1073741824
    restart: always
    volumes:
      - "./docker/tmp/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - proxy

  