<?php

namespace App\Http\Controllers;

use App\Http\Resources\LocationCollectionResource;
use App\Http\Resources\LocationResource;
use App\Models\Location;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;

class LocationsController extends Controller
{
    public $model = Location::class;

    public $resource = LocationResource::class;

    public $resourceCollection = LocationCollectionResource::class;

    public $fillableFields = ['name', 'street', 'number', 'zip_code', 'complement', 'city_id'];

    public function destroy(Location $location)
    {
        DB::table('store_location')->where('location_id', $location->id)->delete();
        return parent::destroy($location); // TODO: Change the autogenerated stub
    }
}
